version: "22.02"
services:
  GNNforPysics:
    container_name: 'GNNforPysics'
    build: .
    image: 'gnnforpysics/tensorflow:22.02-tf1-py3'
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    volumes:
      - $PWD:/mydir
    working_dir: /mydir
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0']
              count: 1
              capabilities: [gpu]
    command: nvidia-smi
    # command: python /home/run.py
    # command: python -m learning_to_simulate.train --data_path=./tmp/datasets/Water --model_path=./tmp/models/Water --num_steps 500000
