version: "2.4"
services:
  GNNforPysics0:
    container_name: 'GNNforPysics0'
    build: ..
    image: 'gnnforpysics/tensorflow:22.02-tf1-py3'
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    volumes:
      # - $PWD:/mydir
      - ../:/mydir
    working_dir: /mydir
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: 1
              capabilities: [gpu]
    # command: ls -al
    # command: nvidia-smi
    # command: python /home/run.py
    # command: python -m learning_to_simulate.train --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --num_steps 10000
    # command: python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --output_path=./tmp/rollouts/Sand
    # command: python -m learning_to_simulate.render_rollouts --rollout_path=./tmp/rollouts/Sand --test_num=100
    command: >
      bash -c "
        python -m learning_to_simulate.train --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --num_steps 10000 &&
        python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --output_path=./tmp/rollouts/Sand $$
        "
    # command: >
    #   bash -c "
    #     python -m learning_to_simulate.train --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --num_steps 100000 &&
    #     python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Sand --model_path=./tmp/models/Sand --output_path=./tmp/rollouts/Sand $$
    #     python -m learning_to_simulate.render_rollouts --rollout_path=./tmp/rollouts/Sand --test_num=100
    #     "
