version: "2.4"
services:
  # GNNforPysics9:
  GNNforPysics1:
    # container_name: 'GNNforPysics9'
    container_name: 'GNNforPysics1'
    build: ..
    image: 'gnnforpysics/tensorflow:22.02-tf1-py3'
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    volumes:
      # - $PWD:/mydir
      - ../:/mydir
    working_dir: /mydir
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['9']
              device_ids: ['1']
              # count: 1
              capabilities: [gpu]
    # command: ls -al
    # command: nvidia-smi -l
    # command: python /home/run.py
    # command: python -m learning_to_simulate.train --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --num_steps 10000
    # command: python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --output_path=./tmp/rollouts/Water-3D
    # command: python -m learning_to_simulate.render_rollouts --rollout_path=./tmp/rollouts/Water-3D --test_num=100
    # command: >
    #   bash -c "
    #     python -m learning_to_simulate.train --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --num_steps 10000 &&
    #     python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --output_path=./tmp/rollouts/Water-3D $$
    #     "
    command: >
      bash -c "
        python -m learning_to_simulate.train --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --num_steps 400000 &&
        python -m learning_to_simulate.train --mode="eval_rollout" --data_path=./tmp/datasets/Water-3D --model_path=./tmp/models/Water-3D --output_path=./tmp/rollouts/Water-3D $$
        python -m learning_to_simulate.render_rollouts --rollout_path=./tmp/rollouts/Water-3D --test_num=100
        "
